import type { Metadata } from 'next'
import { Oxanium, Inter } from 'next/font/google'
import './globals.css'
import { NeonAuthProviders } from '@/providers/neon-auth-ui-provider'

const oxanium = Oxanium({
  variable: '--font-oxanium',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`dark ${inter.variable} ${oxanium.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col bg-background text-foreground'>
        <NeonAuthProviders>{children}</NeonAuthProviders>
      </body>
    </html>
  )
}
